server:
  port: 8888

management:
  context-path: /admin

spring:
  profiles:
     active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

endpoints:
  cors:
    allowedOrigins: '*'
    allowedMethods: POST, GET, OPTIONS, DELETE
    maxAge: 3600
    allowedHeaders: x-requested-with, authorization
